app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_bundle_api:
    type:     rest
    prefix:   /api/v1
    resource: "@AppBundle/Resources/config/api-rest-routing.yml"